<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/privacy/dlp/v2beta2/storage.proto

namespace Google\Cloud\Dlp\V2beta2;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Message defining a custom regular expression.
 *
 * Generated from protobuf message <code>google.privacy.dlp.v2beta2.CustomInfoType.Regex</code>
 */
class CustomInfoType_Regex extends \Google\Protobuf\Internal\Message
{
    /**
     * Pattern defining the regular expression.
     *
     * Generated from protobuf field <code>string pattern = 1;</code>
     */
    private $pattern = '';

    public function __construct() {
        \GPBMetadata\Google\Privacy\Dlp\V2Beta2\Storage::initOnce();
        parent::__construct();
    }

    /**
     * Pattern defining the regular expression.
     *
     * Generated from protobuf field <code>string pattern = 1;</code>
     * @return string
     */
    public function getPattern()
    {
        return $this->pattern;
    }

    /**
     * Pattern defining the regular expression.
     *
     * Generated from protobuf field <code>string pattern = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPattern($var)
    {
        GPBUtil::checkString($var, True);
        $this->pattern = $var;

        return $this;
    }

}

