<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/privacy/dlp/v2beta2/dlp.proto

namespace Google\Cloud\Dlp\V2beta2;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Request for scheduling a scan of a data subset from a Google Platform data
 * repository.
 *
 * Generated from protobuf message <code>google.privacy.dlp.v2beta2.InspectDataSourceRequest</code>
 */
class InspectDataSourceRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * The parent resource name, for example projects/my-project-id.
     *
     * Generated from protobuf field <code>string parent = 1;</code>
     */
    private $parent = '';
    /**
     * A configuration for the job.
     *
     * Generated from protobuf field <code>.google.privacy.dlp.v2beta2.InspectJobConfig job_config = 2;</code>
     */
    private $job_config = null;
    /**
     * Optional job ID to use for the created job. If not provided, a job ID will
     * automatically be generated. Must be unique within the project. The job ID
     * can contain uppercase and lowercase letters, numbers, and hyphens; that is,
     * it must match the regular expression: `[a-zA-Z\\d-]+`. The maximum length
     * is 100 characters. Can be empty to allow the system to generate one.
     *
     * Generated from protobuf field <code>string job_id = 3;</code>
     */
    private $job_id = '';

    public function __construct() {
        \GPBMetadata\Google\Privacy\Dlp\V2Beta2\Dlp::initOnce();
        parent::__construct();
    }

    /**
     * The parent resource name, for example projects/my-project-id.
     *
     * Generated from protobuf field <code>string parent = 1;</code>
     * @return string
     */
    public function getParent()
    {
        return $this->parent;
    }

    /**
     * The parent resource name, for example projects/my-project-id.
     *
     * Generated from protobuf field <code>string parent = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setParent($var)
    {
        GPBUtil::checkString($var, True);
        $this->parent = $var;

        return $this;
    }

    /**
     * A configuration for the job.
     *
     * Generated from protobuf field <code>.google.privacy.dlp.v2beta2.InspectJobConfig job_config = 2;</code>
     * @return \Google\Cloud\Dlp\V2beta2\InspectJobConfig
     */
    public function getJobConfig()
    {
        return $this->job_config;
    }

    /**
     * A configuration for the job.
     *
     * Generated from protobuf field <code>.google.privacy.dlp.v2beta2.InspectJobConfig job_config = 2;</code>
     * @param \Google\Cloud\Dlp\V2beta2\InspectJobConfig $var
     * @return $this
     */
    public function setJobConfig($var)
    {
        GPBUtil::checkMessage($var, \Google\Cloud\Dlp\V2beta2\InspectJobConfig::class);
        $this->job_config = $var;

        return $this;
    }

    /**
     * Optional job ID to use for the created job. If not provided, a job ID will
     * automatically be generated. Must be unique within the project. The job ID
     * can contain uppercase and lowercase letters, numbers, and hyphens; that is,
     * it must match the regular expression: `[a-zA-Z\\d-]+`. The maximum length
     * is 100 characters. Can be empty to allow the system to generate one.
     *
     * Generated from protobuf field <code>string job_id = 3;</code>
     * @return string
     */
    public function getJobId()
    {
        return $this->job_id;
    }

    /**
     * Optional job ID to use for the created job. If not provided, a job ID will
     * automatically be generated. Must be unique within the project. The job ID
     * can contain uppercase and lowercase letters, numbers, and hyphens; that is,
     * it must match the regular expression: `[a-zA-Z\\d-]+`. The maximum length
     * is 100 characters. Can be empty to allow the system to generate one.
     *
     * Generated from protobuf field <code>string job_id = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setJobId($var)
    {
        GPBUtil::checkString($var, True);
        $this->job_id = $var;

        return $this;
    }

}

